# Generated by Django 4.2.7 on 2023-11-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Не удалось')], default='pending', max_length=20),
        ),
    ]
